// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACGxzhoYS_W0iYPnipykapN3pSZ80swjY',
    appId: '1:10858662705:web:abfca18b036689b0ab7e10',
    messagingSenderId: '10858662705',
    projectId: 'babylonassignment',
    authDomain: 'babylonassignment.firebaseapp.com',
    storageBucket: 'babylonassignment.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxzwklsAORE2WeZ4jAQs2RCCDvXv-9oR8',
    appId: '1:10858662705:android:516dec9795bbf89bab7e10',
    messagingSenderId: '10858662705',
    projectId: 'babylonassignment',
    storageBucket: 'babylonassignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Naw6MpNJxmFEpQwlnyY_bYHfRlp48J0',
    appId: '1:10858662705:ios:26e4c493eceed8fcab7e10',
    messagingSenderId: '10858662705',
    projectId: 'babylonassignment',
    storageBucket: 'babylonassignment.firebasestorage.app',
    iosBundleId: 'com.example.babylonAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1Naw6MpNJxmFEpQwlnyY_bYHfRlp48J0',
    appId: '1:10858662705:ios:26e4c493eceed8fcab7e10',
    messagingSenderId: '10858662705',
    projectId: 'babylonassignment',
    storageBucket: 'babylonassignment.firebasestorage.app',
    iosBundleId: 'com.example.babylonAssignment',
  );
}
